### ISSUE TITLE
插件启动时有一个 critical错误,但是不影响使用

### ISSUE THREAD

**Issue by neotaburiss** [Shaun-Fong/SubtaskDescription#1]
使用环境: docker版本
应用程序版本： master.02871400
PHP 版本： 8.0.14
PHP SAPI： fpm-fcgi
HTTP客户端 cURL
系统： Linux 4.19.94-Unraid
数据库驱动： mysql
数据库版本： 10.4.15-MariaDB-1:10.4.15+maria~bionic-log
浏览器： Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36

错误提示(每次启动时会提示,但是不影响使用)
PHP message: [critical] Subtaskdescription: Unable to load this plugin class: \Kanboard\Plugin\Subtaskdescription\Plugin"
2022/04/20 15:03:33 [error] 14#14: *4691 FastCGI sent in stderr: "PHP message: [critical] Subtaskdescription: Unable to load this plugin class: \Kanboard\Plugin\Subtaskdescription\Plugin" while reading response header from upstream, client: 192.168.1.38, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.149:9095"

这里特别感谢下作者, 这个插件的功能非常实用,配合PITM插件,可以直接在子任务描述里图文混排

我这里还有几个感觉kanboard现在缺少的功能,不知道作者有空能否实现(有酬, 绿色聊天软件 base64 d2VjaGF0OjEzNTg2NTU2Mzc1):

1. 最需要的,附件按名字. 上传时间, 上传人排列,因为现在附件上传一多就很难找到
2. 子任务能否分配给一个组,因为现在是只能分配到个人
3. 子任务能否设置一个提醒系统

**Comment by Shaun-Fong** [comment]
我不觉得是插件本身的问题，应该是你的环境配置问题。去看一下`php-fpm`的日志（`/var/log/php-fpm/`）。

**Comment by neotaburiss** [comment]
> 我不觉得是插件本身的问题，应该是你的环境配置问题。去看一下`php-fpm`的日志（`/var/log/php-fpm/`）。

不是一个专业的人员..不知道怎么看....现在用的很不错,也不管这个了

另外作者.后面三个功能不考虑下吗....真的很需要

**Comment by Shaun-Fong** [comment]
> > 我不觉得是插件本身的问题，应该是你的环境配置问题。去看一下`php-fpm`的日志（`/var/log/php-fpm/`）。
> 
> 不是一个专业的人员..不知道怎么看....现在用的很不错,也不管这个了
> 
> 另外作者.后面三个功能不考虑下吗....真的很需要

那你可以尝试一下不用docker。宝塔搭好直接配置kanboard我用着没什么问题。

你说的内容可以有其它方式代替，附加太多你可以多创建几个任务来分类管理。
子任务你可以多创建几个嘛。
任务提醒配置好邮箱就行的，自动动作里面加就可以了。

提醒一下，我开源是用爱发电，我没任何收益，所以没啥义务要必须完成什么功能。当然你要请我喝杯咖啡我很乐意哈哈😄😄

**Comment by neotaburiss** [comment]
明白,谢谢你的建议,感谢

因为现在kanboard是开始维护模式了, 插件开发最近几年也基本停了,我也是想抓住最后一根稻草, 哈哈

kanboard我们从去年开始用,感觉还是比较符合中国人的使用习惯的
