### ISSUE TITLE
备注不按markdown的语法显示

### ISSUE THREAD

**Issue by neotaburiss** [Shaun-Fong/SubtaskDescription#2]
最近使用中发现备注不按markdown的语法显示
![image](https://user-images.githubusercontent.com/78628322/166881956-3415201a-5b65-4b3e-932f-6a4dcfbd9c15.png)
如上,本身是需要高亮显示的, 另外没有换行也有点不方便

不过有可能是我用了markdown plus的插件的原因,但是没有这个插件又用不了PITM插件(可以在备注里插入图片)

作者如果有空能否帮我看下这个问题

使用环境: docker版本
应用程序版本： master.02871400
PHP 版本： 8.0.14
PHP SAPI： fpm-fcgi
HTTP客户端 cURL
系统： Linux 4.19.94-Unraid
数据库驱动： mysql
数据库版本： 10.4.15-MariaDB-1:10.4.15+maria~bionic-log
浏览器： Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36

**Comment by Shaun-Fong** [comment]
已修复 ([v1.1.1](https://github.com/Shaun-Fong/SubtaskDescription/releases/tag/1.1.1))
