### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by RainerBielefeld** [Shaun-Fong/SubtaskDescription#3]
I did a test – Results:
* Will not install from Plugins Directory (no new folderin plugins folder added). 
* Will not be recognized if installed from unzipped Plugin Folder.   

Does not work at all. Any Ideas? 

My system:
KANBOARD Version: 1.2.24
PHP Version: 8.1.7
PHP SAPI: fpm-fcgi
HTTP-Client: cURL
OS Version: Linux 4.15.0-188-generic
Datenbanktreiber: mysql
Datenbank Version: 5.7.37-nmm1-log

**Comment by RainerBielefeld** [comment]
Problem might be limited to mySystem, worked fine for [alfredb](https://kanboard.discourse.group/u/alfredb), see [forum](https://kanboard.discourse.group/t/issues-with-plugins/2435)!

**Comment by Shaun-Fong** [comment]
> Problem might be limited to mySystem, worked fine for [alfredb](https://kanboard.discourse.group/u/alfredb), see [forum](https://kanboard.discourse.group/t/issues-with-plugins/2435)!

I'm glad you solved your problem!
