### ISSUE TITLE
task2pdf导出时不显示SubtaskDescription里插入的图片

### ISSUE THREAD

**Issue by neotaburiss** [Shaun-Fong/SubtaskDescription#4]
首先说下,配合PITM插件可以在SubtaskDescription描述栏里插入图片

但是用最新的task2pdf导出pdf时, 不显示SubtaskDescription的图片, 但同样PITM插入在评论中的图片是可以正常显示的....
![image](https://user-images.githubusercontent.com/78628322/200994502-97d09257-0e1b-44e1-b18f-5ad1df190d95.png)

作者能否看下是task2pdf的原因还是说需要在SubtaskDescription插件里修改

**Comment by Shaun-Fong** [comment]
我已经更换了看板，所以没法debug。
but any pr is welcome
