### ISSUE TITLE
A fix for mysql issue

### ISSUE THREAD

**Issue by aljawaid** [Shaun-Fong/SubtaskDescription#5]
https://github.com/Shaun-Fong/SubtaskDescription/blob/1d8035f550a28688030d21632022f44bf49afd98/Schema/Mysql.php#L11

https://kanboard.discourse.group/t/issues-with-plugins/2435/18?u=aljawaid

Credit to @alfredbuehler for suggesting the fix in the forum.

I created an issue so it would be easier for you to update and release a new version of the plugin so the plugin is available to more users within the Kanboard Extensions Directory.

**Comment by Shaun-Fong** [comment]
that's great, thanks !
